src/MockSchoolManagement.Mvc/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MockSchoolManagement.Application.Courses;
using MockSchoolManagement.Application.Courses.Dtos;
using MockSchoolManagement.EntityFrameworkCore;
using MockSchoolManagement.Infrastructure.Repositories;
using MockSchoolManagement.Models;
using MockSchoolManagement.ViewModels;
using System.Linq;
using System.Threading.Tasks;

namespace MockSchoolManagement.Controllers
{
    public class CourseController : Controller
    {
        private readonly AppDbContext _dbcontext;

        private readonly IRepository<Course, int> _courseRepository;
        private readonly ICourseService _courseService;
        private readonly IRepository<CourseAssignment, int> _courseAssignmentsRepository;
        private readonly IRepository<Department, int> _departmentRepository;

        public CourseController(
            IRepository<Course, int> courseRepository,
            ICourseService courseService,
            IRepository<Department, int> departmentRepository,
            IRepository<CourseAssignment, int> courseAssignmentsRepository,
            AppDbContext dbcontext)
        {
            _courseRepository = courseRepository;
            _courseService = courseService;
            _departmentRepository = departmentRepository;
            _courseAssignmentsRepository = courseAssignmentsRepository;
            _dbcontext = dbcontext;
        }

        // 不填写 [HttpGet]默认为处理GET请求
        public async Task<ActionResult> Index(GetCourseInput input)
        {
            var models = await _courseService.GetPaginatedResult(input);
            return View(models);
        }

        #region 添加课程

        public ActionResult Create()
        {
            var dtos = DepartmentsDropDownList();
            CourseCreateViewModel courseCreateViewModel = new CourseCreateViewModel
            {
                DepartmentList = dtos
            };

            return View(courseCreateViewModel);
        }

        [HttpPost]
        public async Task<ActionResult> Create(CourseCreateViewModel input)
        {
            if (ModelState.IsValid)
            {
                Course course = new Course
                {
                    CourseID = input.CourseID,
                    Title = input.Title,
                    Credits = input.Credits,
                    DepartmentID = input.DepartmentID
                };

                await _courseRepository.InsertAsync(course);

                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        #endregion 添加课程

        #region 编辑功能

        public IActionResult Edit(int? courseId)
        {
            if (!courseId.HasValue)
            {
                ViewBag.ErrorMessage = $"课程编号{courseId}的信息不存在，请重试。";
                return View("NotFound");
            }

            var course = _courseRepository.FirstOrDefault(a => a.CourseID == courseId);

            if (course == null)
            {
                ViewBag.ErrorMessage = $"课程编号{courseId}的信息不存在，请重试。";
                return View("NotFound");
            }
            var dtos = DepartmentsDropDownList(course.DepartmentID);
            CourseCreateViewModel courseCreateViewModel = new CourseCreateViewModel
            {
                DepartmentList = dtos,
                CourseID = course.CourseID,
                Credits = course.Credits,
                Title = course.Title,
                DepartmentID = course.DepartmentID
            };
            return View(courseCreateViewModel);
        }

        [HttpPost]
        public IActionResult Edit(CourseCreateViewModel input)
        {
            if (ModelState.IsValid)
            {
                var course = _courseRepository.FirstOrDefault(a => a.CourseID == input.CourseID);
                if (course != null)
                {
                    course.Credits = input.Credits;
                    course.DepartmentID = input.DepartmentID;
                    course.Title = input.Title;
                    _courseRepository.Update(course);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.ErrorMessage = $"课程编号{input.CourseID}的信息不存在，请重试。";
                    return View("NotFound");
                }
            }
            return View(input);
        }

        #endregion 编辑功能

        public async Task<ViewResult> Details(int courseId)
        {
            var course = await _courseRepository.GetAll().Include(a => a.Department).FirstOrDefaultAsync(a => a.CourseID == courseId);

            //判断学生信息是否存在
            if (course == null)
            {
                ViewBag.ErrorMessage = $"课程编号{courseId}的信息不存在，请重试。";
                return View("NotFound");
            }

            return View(course);
        }

        #region 删除功能

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _courseRepository.FirstOrDefaultAsync(a => a.CourseID == id);

            if (model == null)
            {
                ViewBag.ErrorMessage = $"课程编号{id}的信息不存在，请重试。";
                return View("NotFound");
            }

            // await _courseAssignmentsRepository.DeleteAsync(a => a.CourseID == model.CourseID);

            await _courseRepository.DeleteAsync(a => a.CourseID == id);
            return RedirectToAction(nameof(Index));
        }

        #endregion 删除功能

        #region 修改课程学分

        public IActionResult UpdateCourseCredits()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateCourseCredits(int? multiplier)
        {
            if (multiplier != null)
            {
                ViewBag.RowsAffected =
                    //通过ExecuteSqlRawAsync方法执行sql命令
                    await _dbcontext.Database.ExecuteSqlRawAsync(
                        "UPDATE School.Course SET Credits = Credits * {0}",
                        parameters: multiplier);
            }
            return View();
        }

        #endregion 修改课程学分

        /// <summary>
        /// 院系的下拉列表
        /// </summary>
        /// <param name="selectedDepartment"> </param>
        private SelectList DepartmentsDropDownList(object selectedDepartment = null)
        {
            var models = _departmentRepository.GetAll().OrderBy(a => a.Name).AsNoTracking().ToList();

            var dtos = new SelectList(models, "DepartmentID", "Name", selectedDepartment);

            return dtos;
        }
    }
}

src/MockSchoolManagement.Mvc/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MockSchoolManagement.Application.Teachers;
using MockSchoolManagement.Infrastructure.Repositories;
using MockSchoolManagement.Models;
using MockSchoolManagement.ViewModels;
using MockSchoolManagement.ViewModels.Teachers;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MockSchoolManagement.Controllers
{
    public class TeacherController : Controller
    {
        private readonly ITeacherService _teacherService;
        private readonly IRepository<Teacher, int> _teacherRepository;
        private readonly IRepository<Course, int> _courseRepository;
        private readonly IRepository<OfficeLocation, int> _officeLoactionRepository;
        private readonly IRepository<CourseAssignment, int> _courseAssignmentRepository;
        private readonly IRepository<Department,int> _departmentRepository;


        public TeacherController(ITeacherService teacherService, IRepository<Teacher, int> teacherRepository, IRepository<Course, int> courseRepository, IRepository<OfficeLocation, int> officeLoactionRepository, IRepository<CourseAssignment, int> courseAssignmentRepository,
            IRepository<Department, int> departmentRepository)
        {
            _teacherService = teacherService;
            _teacherRepository = teacherRepository;
            _courseRepository = courseRepository;
            _officeLoactionRepository = officeLoactionRepository;
            _courseAssignmentRepository = courseAssignmentRepository;
            _departmentRepository = departmentRepository;
        }

        public async Task<IActionResult> Index(GetTeacherInput input)
        {
            var models = await _teacherService.GetPagedTeacherList(input);

            var dto = new TeacherListViewModel();

            if (input.Id != null)
            {       //查询老师教授的课程列表
                var teacher = models.Data.FirstOrDefault(a => a.Id == input.Id.Value);
                if (teacher != null)
                {
                    dto.Courses = teacher.CourseAssignments.Select(a => a.Course).ToList();
                }
                dto.SelectedId = input.Id.Value;
            }

            if (input.CourseId.HasValue)
            {//查询该课程下有多少学生报名
                var course = dto.Courses.FirstOrDefault(a => a.CourseID == input.CourseId.Value);
                if (course != null)
                {
                    dto.StudentCourses = course.StudentCourses.ToList();
                }
                dto.SelectedCourseId = input.CourseId.Value;
            }
            dto.Teachers = models;

            return View(dto);
        }

        public IActionResult Create()
        {
            //var allCourses = _departmentRepository.GetAllList();
            //var viewModel = new List<AssignedDepartmentViewModel>();
            //foreach (var course in allCourses)
            //{
            //    viewModel.Add(new AssignedDepartmentViewModel
            //    {
            //        DepartmentId = course.DepartmentID,
            //        Name = course.Name,
            //        IsSelected = false
            //    });
            //}
            //ViewBag.Departments = viewModel;

            var viewModel = new TeacherCreateViewModel();
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TeacherCreateViewModel input)
        {
            if (ModelState.IsValid)
            {
                var teacher = new Teacher
                {
                    HireDate = input.HireDate,
                    Name = input.Name,
                    UserCode=input.UserCode,
                    UserSex=input.UserSex,
                    Age=input.Age,
                    Title=input.Title,
                    TeacherPhone=input.TeacherPhone,
                    Address=input.Address,
                    TeachCourseName=input.TeachCourseName,
                    TeachClass=input.TeachClass
                    ////OfficeLocation = input.OfficeLocation,
                    //CourseAssignments = new List<CourseAssignment>()
                };
                //var courses = input.AssignedCourses.Where(a => a.IsSelected == true).ToList();
                //foreach (var item in courses)
                //{
                //    teacher.CourseAssignments.Add(new CourseAssignment { CourseID = item.CourseID, TeacherID = teacher.Id });
                //}
                await _teacherRepository.InsertAsync(teacher);
                return RedirectToAction(nameof(Index));
            }

            return View(input);
        }



        public async Task<IActionResult> Edit(int? id)
        {
            var model = await _teacherRepository.GetAll()
                    .AsNoTracking().FirstOrDefaultAsync(a => a.Id == id);

            if (model == null)
            {
                ViewBag.ErrorMessage = $"教师信息ID为{id}的信息不存在，请重试。";
                return View("NotFound");
            }
            //处理业务的视图模型
            var dto = new TeacherCreateViewModel
            {
                HireDate = model.HireDate,
                Name = model.Name,
                UserCode = model.UserCode,
                UserSex = model.UserSex,
                Age = model.Age,
                Title = model.Title,
                TeacherPhone = model.TeacherPhone,
                Address = model.Address,
                TeachCourseName = model.TeachCourseName,
                TeachClass = model.TeachClass
            };
            //从课程列表中处理哪些课程已经分配哪些为分配
            //var assignedCourses = AssignedCourseDroupDownList(model);
            //dto.AssignedCourses = assignedCourses;
            return View(dto);
        }


        [HttpPost, ActionName("Edit")]
        public async Task<IActionResult> EditPost(TeacherCreateViewModel input)
        {
            if (ModelState.IsValid)
            {
                var teacher = await _teacherRepository.GetAll().Include(i => i.OfficeLocation)
                   .Include(i => i.CourseAssignments)
                       .ThenInclude(i => i.Course)
                   .FirstOrDefaultAsync(m => m.Id == input.Id);

                if (teacher == null)
                {
                    ViewBag.ErrorMessage = $"教师信息ID为{input.Id}的信息不存在，请重试。";
                    return View("NotFound");
                }

                teacher.HireDate = input.HireDate;
                teacher.Name = input.Name;
                teacher.UserCode = input.UserCode;
                teacher.UserSex = input.UserSex;
                teacher.Age = input.Age;
                teacher.Title = input.Title;
                teacher.TeacherPhone = input.TeacherPhone;
                teacher.Address = input.Address;
                teacher.TeachCourseName = input.TeachCourseName;
                teacher.TeachClass = input.TeachClass;

                //teacher.OfficeLocation = input.OfficeLocation;
                //teacher.CourseAssignments = new List<CourseAssignment>();
                //从视图中获取被选中的课程信息
                //var courses = input.AssignedCourses.Where(a => a.IsSelected == true).ToList();

                //foreach (var item in courses)
                //{  //将选中的课程信息赋值到导航属性CourseAssignments中
                //    teacher.CourseAssignments.Add(new CourseAssignment { CourseID = item.CourseID, TeacherID = teacher.Id });
                //}

                await _teacherRepository.UpdateAsync(teacher);

                return RedirectToAction(nameof(Index));
            }

            return View(input);
        }

     
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _teacherRepository.FirstOrDefaultAsync(a => a.Id == id);

            if (model == null)
            {
                ViewBag.ErrorMessage = $"教师id为{id}的信息不存在，请重试。";
                return View("NotFound");
            }

            await _officeLoactionRepository.DeleteAsync(a => a.TeacherId == model.Id);
            await _courseAssignmentRepository.DeleteAsync(a => a.TeacherID == model.Id);
            await _teacherRepository.DeleteAsync(a => a.Id == id);
            return RedirectToAction(nameof(Index));
        }


        // Details视图接收加密后的StudentID
        public async Task<IActionResult> Details(int id)
        {
            var model = await _teacherRepository.GetAll()
                    .AsNoTracking().FirstOrDefaultAsync(a => a.Id == id);

            if (model == null)
            {
                ViewBag.ErrorMessage = $"教师信息ID为{id}的信息不存在，请重试。";
                return View("NotFound");
            }
            //处理业务的视图模型
            var dto = new TeacherCreateViewModel
            {
                HireDate = model.HireDate,
                Name = model.Name,
                UserCode = model.UserCode,
                UserSex = model.UserSex,
                Age = model.Age,
                Title = model.Title,
                TeacherPhone = model.TeacherPhone,
                Address = model.Address,
                TeachCourseName = model.TeachCourseName,
                TeachClass = model.TeachClass
            };
            //从课程列表中处理哪些课程已经分配哪些为分配
            //var assignedCourses = AssignedCourseDroupDownList(model);
            //dto.AssignedCourses = assignedCourses;
            return View(dto);
        }


        /// <summary>
        /// 处理课程列表是否被选中
        /// </summary>
        /// <param name="teacher"></param>
        /// <returns></returns>
        private List<AssignedCourseViewModel> AssignedCourseDroupDownList(Teacher teacher)
        {//获取课程列表
            var allCourses = _courseRepository.GetAllList();
            //获取老师当前教授的课程
            var teacherCourses = new HashSet<int>(teacher.CourseAssignments.Select(c => c.CourseID));

            var viewModel = new List<AssignedCourseViewModel>();
            foreach (var course in allCourses)
            {

src/MockSchoolManagement.Mvc/Views/Shared/NotFound.cshtml
@{ ViewBag.Title = "页面不存在"; }

 

<div class="alert alert-danger mt-1 mb-1">
    <h4>404 Not Found 错误 :</h4>
    <hr />
    <h5>
        @ViewBag.ErrorMessage
    </h5>
</div>

<a asp-controller="home" asp-action="index" class="btn btn-outline-success"
   style="width:auto">  点击此处返回首页</a>
 

src/MockSchoolManagement.Mvc/Views/Shared/_Layout.cshtml
<html>
<head>
    <meta name="viewport" content="width=device-width" />

	<environment include="Development">
		<link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
		<link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
	</environment>

	<environment exclude="Development">
		<link rel="stylesheet"
			  href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
			  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
			  crossorigin="anonymous"
			  asp-fallback-href="~/lib/twitter-bootstrap/css/bootstrap.min.css"
			  asp-fallback-test-class="sr-only"
			  asp-fallback-test-property="position"
			  asp-fallback-test-value="absolute"
			  asp-suppress-fallback-integrity="true" />
		<link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
	</environment>

    <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <a class="navbar-brand" asp-controller="home" asp-action="index">
                <img src="~/images/banner.png" width="320" height="30" />
            </a>
            <button class="navbar-toggler"
                    type="button"
                    data-toggle="collapse"
                    data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            @using Microsoft.AspNetCore.Identity
            @inject SignInManager<ApplicationUser> _signInManager
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">

                         @if (User.IsInRole("Admin")|| User.IsInRole("教师"))
                         {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="home" asp-action="index">学生管理</a>
                    </li>
                    @*<li class="nav-item">
            <a class="nav-link" asp-controller="Course" asp-action="index">课程管理</a>
        </li>*@
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Teacher" asp-action="index">教师管理</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Departments" asp-action="index">班级管理</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="home" asp-action="AddressBook">通讯录</a>
                    </li>
                    @*<li class="nav-item">
            <a class="nav-link" href="/swagger">Swagger-UI</a>
        </li>*@
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="home" asp-action="About">汇总统计</a>
                    </li>
                         }

                    @if (_signInManager.IsSignedIn(User))
                    {

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle"
                       href="#"
                       id="navbarDropdownMenuLink"
                       data-toggle="dropdown"
                       aria-haspopup="true"
                       aria-expanded="false">
                        管理
                    </a>



                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

                        @if (User.IsInRole("Admin"))
                        {
                <a class="dropdown-item" asp-controller="Admin" asp-action="ListUsers">用户列表</a>
                                    <a class="dropdown-item" asp-controller="Admin" asp-action="ListRoles">角色列表</a>}
                        <a class="dropdown-item" asp-controller="Account"
                           asp-action="ChangePassword">
                            密码管理
                        </a>
                    </div>
                </li>}
                </ul>
                <ul class="navbar-nav ml-auto">
                    @*如果用户已登录，则显示注销链接*@
                    @if (_signInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <form method="post" asp-controller="account" asp-action="logout">
                                <button type="submit" style="width:auto"
                                        class="nav-link btn btn-link py-0">
                                    注销 @User.Identity.Name
                                </button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="account" asp-action="login">
                                登录
                            </a>
                        </li>
                    }
                </ul>
            </div>
        </nav>
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>
        <script src="~/lib/jquery-validate/jquery.validate.js"></script>
        <script src="~/lib/jquery-validate-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>
        <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validate-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    </environment>

    @if (IsSectionDefined("Scripts"))
    {@RenderSection("Scripts", required:
false)}
</body>
</html>

src/MockSchoolManagement.Mvc/Views/Shared/_Pagination.cshtml
<div>
    <ul class="pagination">

        <li class="page-item @(!Model.ShowFirst? "disabled":"")">
            <a asp-route-CurrentPage="1" asp-route-FilterText="@Model.FilterText" asp-route-Sorting="@Model.Sorting" class="page-link">
                <i class="fa fa-fast-backward"></i>
            </a>
        </li>

        <li class="page-item @(!Model.ShowPrevious? "disabled":"")">
            <a asp-route-CurrentPage="@(Model.CurrentPage -1)" asp-route-FilterText="@Model.FilterText" asp-route-Sorting="@Model.Sorting" class="page-link">
                <i class="fa fa-step-backward"></i>
            </a>
        </li>

        @for (var i = 1; i <= Model.TotalPages; i++)
        {
            <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                <a asp-route-currentpage="@i" asp-route-FilterText="@Model.FilterText" asp-route-Sorting="@Model.Sorting" class="page-link">@i</a>
            </li>
        }

        <li class="page-item  @(!Model.ShowNext? "disabled":"")">
            <a asp-route-CurrentPage="@(Model.CurrentPage + 1)" asp-route-FilterText="@Model.FilterText" asp-route-Sorting="@Model.Sorting" class="page-link">
                <i class="fa fa-step-forward"></i>
            </a>
        </li>

        <li class="page-item  @(!Model.ShowLast? "disabled":"")">
            <a asp-route-CurrentPage="@Model.TotalPages" asp-route-FilterText="@Model.FilterText" asp-route-Sorting="@Model.Sorting" class="page-link">
                <i class="fa fa-fast-forward"></i>
            </a>
        </li>
    </ul>
</div>